patient_homepage:
    path:     /patient/{id}
    defaults: { _controller: PatientBundle:Patient:index, id: 1 }

patients_list:
    path: /patients
    defaults: { _controller: PatientBundle:PatientList:index }
patients_load:
    path: /patients_load
    defaults: { _controller: PatientBundle:PatientList:load }

patient_delete:
    path: /patient_delete/{id}
    defaults: { _controller: PatientBundle:Patient:delete, id: empty }

patient_edit:
    path: /patient_edit/{id}
    defaults: { _controller: PatientBundle:Patient:edit, id: 1 }

patient_new:
    path: /patient_new
    defaults: { _controller: PatientBundle:Patient:new }

patient_save:
    path: /patient_save
    defaults: { _controller: PatientBundle:Patient:save }