patient_disease:
    resource: "@PatientDiseaseBundle/Resources/config/routing.yml"
    prefix:   /

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /

disease:
    resource: "@DiseaseBundle/Resources/config/routing.yml"
    prefix:   /

patient:
    resource: "@PatientBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

lancer_lance:
    resource: "@LancerLanceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
