patient_disease_homepage:
    path:     /patient_disease/{id}
    defaults: { _controller: PatientDiseaseBundle:PatientDisease:index, id: no }

patient_disease_edit:
    path:   /patient_disease_edit/{id}
    defaults: { _controller: PatientDiseaseBundle:PatientDisease:edit, id: no}

patient_disease_new:
    path:   /patient_disease_new/{id}
    defaults: { _controller: PatientDiseaseBundle:PatientDisease:new, id: no }

patient_disease_save:
    path:   /patient_disease_save
    defaults: { _controller: PatientDiseaseBundle:PatientDisease:save }
    requirements:
            _method: POST

patient_disease_delete:
    path:   /patient_disease_delete/{id}
    defaults: { _controller: PatientDiseaseBundle:PatientDisease:delete, id: no }
patient_disease_list:
    path: /patient_disease_list/{id}
    defaults: { _controller: PatientDiseaseBundle:PatientDiseaseList:index, id:no }
patient_disease_load:
    path: /patient_disease_load/{id}/{active}
    defaults: { _controller: PatientDiseaseBundle:PatientDiseaseList:load, id:no, active: 0}
patient_disease_user_load:
    path: /patient_disease_load_user/{active}
    defaults: { _controller: PatientDiseaseBundle:PatientDiseaseList:forUserLoad, active: 0}